#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.5 on Thu Mar 13 16:50:43 2008

import wx
import wx.lib.iewin
import global_var,download,GUItools
def cgood():
	print "good"
class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.window_1 = wx.SplitterWindow(self, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.window_1_pane_2 = wx.Panel(self.window_1, -1)
        self.window_3 = wx.SplitterWindow(self.window_1_pane_2, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.window_3_pane_2 = wx.Panel(self.window_3, -1)
        self.window_1_pane_1 = wx.Panel(self.window_1, -1)
        self.window_2 = wx.SplitterWindow(self.window_1_pane_1, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.window_2_pane_2 = wx.Panel(self.window_2, -1)
        self.window_2_pane_1 = wx.Panel(self.window_2, -1)
        self.label_1 = wx.StaticText(self.window_2_pane_1, -1, u"本地信息", style=wx.TE_READONLY)
        self.txtLocalPath = wx.TextCtrl(self.window_2_pane_1, -1, u"本地路径")
        self.dirLocal = wx.GenericDirCtrl(self.window_2_pane_1, -1, style=wx.DIRCTRL_SHOW_FILTERS)
        self.label_2 = wx.StaticText(self.window_2_pane_2, -1, u"远程文件信息")
        self.txtRemoteCourse = wx.TextCtrl(self.window_2_pane_2, -1, u"初始课程", style=wx.TE_READONLY)
        self.lstRemoteFile = wx.ListCtrl(self.window_2_pane_2, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.btnDownSingle = wx.Button(self.window_2_pane_2, -1, u"下载选中文件")
        self.btnDownCourse = wx.Button(self.window_2_pane_2, -1, u"下载该课程全部文件")
        self.btnDownAll = wx.Button(self.window_2_pane_2, -1, u"下载所有课程的文件")
        self.btnRefresh = wx.Button(self.window_2_pane_2, -1, u"刷新列表")
        self.window_3_pane_1 = wx.Panel(self.window_3, -1)
        self.label_3 = wx.StaticText(self.window_3_pane_2, -1, u"我的课程")
        self.lstRemoteCourse = wx.ListCtrl(self.window_3_pane_2, -1, style=wx.LC_REPORT|wx.LC_SINGLE_SEL|wx.SUNKEN_BORDER)
        
        #IE控件还不太会用，暂时不弄
        #self.htmlWindow=wx.lib.iewin.IEHtmlWindow(self.window_3_pane_1, -1)
        #
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        self.SetMenuBar(self.frame_1_menubar)
        self.excMenu = wx.Menu()
        self.logItem = wx.MenuItem(self.excMenu, wx.NewId(), (u"登录(&L)"), (u"登录到网络学堂"), wx.ITEM_NORMAL)
        self.excMenu.AppendItem(self.logItem)
        self.setItem = wx.MenuItem(self.excMenu, wx.NewId(), (u"设置(&S)"), (u"设置下载规则"), wx.ITEM_NORMAL)
        self.excMenu.AppendItem(self.setItem)
        self.exitItem = wx.MenuItem(self.excMenu, wx.NewId(), (u"退出(&E)"), (u"退出程序"), wx.ITEM_NORMAL)
        self.excMenu.AppendItem(self.exitItem)
        self.frame_1_menubar.Append(self.excMenu, (u"操作(&A)"))
        self.hlpItem = wx.Menu()
        self.hlpMenu = wx.MenuItem(self.hlpItem, wx.NewId(), (u"帮助"), (u"获取帮助信息"), wx.ITEM_NORMAL)
        self.hlpItem.AppendItem(self.hlpMenu)
        self.about = wx.MenuItem(self.hlpItem, wx.NewId(), (u"关于"), (u"软件说明"), wx.ITEM_NORMAL)
        self.hlpItem.AppendItem(self.about)
        self.frame_1_menubar.Append(self.hlpItem, (u"帮助(&H)"))
        # Menu Bar end
        self.statusBar = self.CreateStatusBar()

        self.__set_properties()
        self.__do_layout()
        GUItools.Frame__init(self)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("Downloader")
        self.SetSize((850, 600))
        self.window_1_pane_1.SetMinSize((850, 400))
        self.window_1_pane_2.SetMinSize((850, 250))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        #sizer_10= wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.FlexGridSizer(4, 1, 0, 0)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.FlexGridSizer(1, 4, 0, 0)
        
        
        
        sizer_4.Add(self.label_1, 0, wx.EXPAND, 0)
        sizer_4.Add(self.txtLocalPath, 0, wx.EXPAND, 0)
        sizer_4.Add(self.dirLocal, 1, wx.EXPAND, 0)
        self.window_2_pane_1.SetSizer(sizer_4)
        sizer_9.Add(self.btnDownSingle,0,0,0)
        sizer_9.Add(self.btnDownCourse,0,0,0)
        sizer_9.Add(self.btnDownAll,0,0,0)
        sizer_9.Add(self.btnRefresh,0,0,0)
        
        #sizer_10.Add(self.htmlWindow)
        #self.window_3_pane_1.SetSizer(sizer_10,wx.EXPAND)
        
        sizer_5.Add(self.label_2, 0, wx.EXPAND, 0)
        sizer_5.Add(self.txtRemoteCourse, 0, wx.EXPAND, 0)
        sizer_5.Add(self.lstRemoteFile, 0,wx.EXPAND,0)
        sizer_5.Add(sizer_9,0,0,0)
        self.window_2_pane_2.SetSizer(sizer_5)
        sizer_5.AddGrowableCol(0, 1)
        sizer_5.AddGrowableRow(2, 1)
        self.window_2.SplitVertically(self.window_2_pane_1, self.window_2_pane_2)
        sizer_2.Add(self.window_2, 1, wx.EXPAND, 0)
        self.window_1_pane_1.SetSizer(sizer_2)
        sizer_8.Add(self.label_3, 0, wx.EXPAND, 0)
        sizer_8.Add(self.lstRemoteCourse, 1, wx.EXPAND, 0)
        self.window_3_pane_2.SetSizer(sizer_8)
        self.window_3.SplitVertically(self.window_3_pane_1, self.window_3_pane_2)
        sizer_3.Add(self.window_3, 1, wx.EXPAND, 0)
        self.window_1_pane_2.SetSizer(sizer_3)
        self.window_1.SplitHorizontally(self.window_1_pane_1, self.window_1_pane_2)
        sizer_1.Add(self.window_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class MainFrame