#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.5 on Thu Mar 20 20:43:49 2008 from E:\Python\WxGladeFrames\wxDownload.wxg

import wx,global_var
import wx.html
import GUItools
class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.panel_4 = wx.Panel(self.panel_1, -1)
        self.panel_7 = wx.Panel(self.panel_4, -1)
        self.panel_3 = wx.Panel(self.panel_1, -1)
        self.panel_6 = wx.Panel(self.panel_3, -1)
        self.panel_5 = wx.Panel(self.panel_3, -1)
        self.sizer_7_staticbox = wx.StaticBox(self.panel_6, -1, _(u"课程公告"))
        self.sizer_10_staticbox = wx.StaticBox(self.panel_4, -1, _(u"本次下载的文件"))
        self.sizer_11_staticbox = wx.StaticBox(self.panel_4, -1, _(u"远程文件信息"))
        self.sizer_6_staticbox = wx.StaticBox(self.panel_5, -1, _(u"我的课程"))
        
        # Menu Bar
        self.mainFrame_menubar = wx.MenuBar()
        self.SetMenuBar(self.mainFrame_menubar)
        self.excMenu = wx.Menu()
        self.logItem = wx.MenuItem(self.excMenu, wx.NewId(), _(u"登录设置"), "", wx.ITEM_NORMAL)
        self.excMenu.AppendItem(self.logItem)
        self.exitItem = wx.MenuItem(self.excMenu, wx.NewId(), _(u"退出"), "", wx.ITEM_NORMAL)
        self.excMenu.AppendItem(self.exitItem)
        self.mainFrame_menubar.Append(self.excMenu, _(u"操作"))
        self.hlpMenu = wx.Menu()
        self.hlpItem = wx.MenuItem(self.hlpMenu, wx.NewId(), _(u"帮助文档"), "", wx.ITEM_NORMAL)
        self.hlpMenu.AppendItem(self.hlpItem)
        self.aboutItem = wx.MenuItem(self.hlpMenu, wx.NewId(), _(u"说明"), "", wx.ITEM_NORMAL)
        self.hlpMenu.AppendItem(self.aboutItem)
        self.mainFrame_menubar.Append(self.hlpMenu, _(u"帮助"))
        # Menu Bar end
        self.statusBar = self.CreateStatusBar(1, 0)
        
        # Tool Bar
        self.mainFrame_toolbar = wx.ToolBar(self, -1)
        self.SetToolBar(self.mainFrame_toolbar)
        self.toolDownAll=self.mainFrame_toolbar.AddLabelTool(wx.NewId(), _(u"下载更新"), wx.Bitmap("bitmaps\\DownAll.bmp", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, _(u"下载所有课件，更新公告"), "")
        self.toolDownAllFiles=self.mainFrame_toolbar.AddLabelTool(wx.NewId(), _(u"下载课件"), wx.Bitmap("bitmaps\\DownFile.bmp", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, _(u"下载所有课件"), "")
        self.toolRefreshNotes=self.mainFrame_toolbar.AddLabelTool(wx.NewId(), _(u"更新公告"), wx.Bitmap("bitmaps\\Notice.bmp", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, _(u"更新所有公告"), "")
        self.tollRefreshAll=self.mainFrame_toolbar.AddLabelTool(wx.NewId(), _(u"刷新"), wx.Bitmap("bitmaps\\Refresh.bmp", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, _(u"刷新所有课件列表"), "")
        self.toolStop=self.mainFrame_toolbar.AddLabelTool(wx.NewId(), _(u"停止"), wx.Bitmap("bitmaps\\Stop.bmp", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, _(u"停止"), "")
        # Tool Bar end
        self.lstRemoteCourse = wx.ListCtrl(self.panel_5, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.html = wx.html.HtmlWindow(self.panel_6, -1)
        self.lstLocalFile = wx.ListCtrl(self.panel_4, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.btnCopy = wx.Button(self.panel_4, -1, _(u"把标记的课件复制到打印文件夹"))
        self.lstRemoteFile = wx.ListCtrl(self.panel_7, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.btnDownMarked = wx.Button(self.panel_7, -1, _(u"下载标记的课件"))
        self.btnMarkAll = wx.Button(self.panel_7, -1, _(u"标记本课程所有课件"))
        self.btnDemarkAll = wx.Button(self.panel_7, -1, _(u"取消所有课件的标记"))
        self.btnRefresh = wx.Button(self.panel_7, -1, _(u"刷新本课程"))
        #self.statusBar = self.CreateStatusBar()
        GUItools.FrameInit(self)
        self.__set_properties()
        self.__do_layout()

        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle(_(u"网络学堂"))
        self.SetSize((900, 600))
        # statusbar fields
        
        self.statusBar.SetFieldsCount(3)
        self.statusBar.SetStatusWidths([1,580,-3])
        self.statusBar.SetStatusText(u"状态：空闲",2)
        self.mainFrame_toolbar.SetToolBitmapSize((50, 50))
        self.mainFrame_toolbar.SetMargins((0, 0))
        self.mainFrame_toolbar.Realize()
        self.panel_5.SetMinSize((200,300))
        self.panel_6.SetMinSize((500,300))
        self.panel_3.SetMinSize((600,300))
        self.panel_7.SetMinSize((300,300))
        self.panel_4.SetMinSize((600,300))
        self.panel_1.SetMinSize((900, 600))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.StaticBoxSizer(self.sizer_11_staticbox, wx.HORIZONTAL)
        sizer_14 = wx.FlexGridSizer(2, 1, 0, 0)
        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.StaticBoxSizer(self.sizer_10_staticbox, wx.HORIZONTAL)
        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        ###########
        sizer_5 = wx.FlexGridSizer(1,2,0,0)
        ##########
        sizer_7 = wx.StaticBoxSizer(self.sizer_7_staticbox, wx.VERTICAL)
        sizer_6 = wx.StaticBoxSizer(self.sizer_6_staticbox, wx.VERTICAL)
        sizer_6.Add(self.lstRemoteCourse, 1, wx.EXPAND, 0)
        self.panel_5.SetSizer(sizer_6)
        sizer_5.Add(self.panel_5, 1, wx.EXPAND, 0)
        sizer_7.Add(self.html, 1, wx.EXPAND, 0)
        self.panel_6.SetSizer(sizer_7)
        sizer_5.Add(self.panel_6, 1, wx.EXPAND, 0)
        self.panel_3.SetSizer(sizer_5)
        ##########
        sizer_5.AddGrowableRow(0)
        sizer_5.AddGrowableCol(1)
        sizer_4.Add(self.panel_3, 1, wx.EXPAND, 0)
        sizer_12.Add(self.lstLocalFile, 1, wx.EXPAND, 0)
        sizer_12.Add(self.btnCopy, 0, 0, 0)
        sizer_10.Add(sizer_12, 1, wx.EXPAND, 0)
        sizer_9.Add(sizer_10, 1, wx.EXPAND, 0)
        sizer_14.Add(self.lstRemoteFile, 1, wx.EXPAND, 0)
        sizer_15.Add(self.btnDownMarked, 0, 0, 0)
        ##########################################
        sizer_15.Add(self.btnMarkAll, 0, 0, 0)
        sizer_15.Add(self.btnDemarkAll, 0, 0, 0)
        ##########################################
        sizer_15.Add(self.btnRefresh, 0, 0, 0)
        sizer_14.Add(sizer_15, 1, wx.EXPAND, 0)
        self.panel_7.SetSizer(sizer_14)
        sizer_14.AddGrowableRow(0)
        sizer_14.AddGrowableCol(0)
        sizer_11.Add(self.panel_7, 1, wx.EXPAND, 0)
        sizer_9.Add(sizer_11, 1, wx.EXPAND, 0)
        sizer_8.Add(sizer_9, 1, wx.EXPAND, 0)
        self.panel_4.SetSizer(sizer_8)
        sizer_4.Add(self.panel_4, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_4)
        sizer_3.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        self.Layout()
        # end wxGlade
# end of class MainFram