#!/usr/bin/python

#
# Rhiju's first python script.
# Just go through and apply Phil's clustering program to
# all these outfiles generated by Rowan -- what are the
# top five clusters?
#
# August 29, 2005
#

from os.path import exists
from math import floor,log10,log,exp
from operator import add
from os import chdir,system,popen,getcwd
from sys import stderr,argv,exit
import sys
from whrandom import random
from math import sqrt
import re
import string

filelist = sys.argv[1]

filein = open(filelist,'r')
fileout= open('%s.clean'%filelist,'w')

lines = filein.readlines()

for line in lines :
     if (not re.search('rms',line)):
          cols = string.split( line)
          sepstring = ' ';
          print >> fileout, sepstring.join(cols[1:-1])

filein.close()
fileout.close()
