# models.py

# All standard Django fields as well as GeoDjango geometry fields and the GeoManager()
# can be imported from django.contrib.gis.db
from django.contrib.gis.db import models

# Used to display html within Admin App
from django.utils.safestring import mark_safe

class WorldBorders(models.Model):
    """
    
    A geographic model based on the V3 of the simplified world borders multipolygon shapefile
    from http://thematicmapping.org/downloads/world_borders.php.
    
    Field names, Django types, and max_lengths were autogenerated using the ogrinspect utility with hand
    edits adding alternative field names and help_text.
    
    Imported using the LayerMapping Utility (requires GDAL) called within the load_data.py script provided
    within this sample project.
    
    """
    name = models.CharField(max_length=50, )
    area = models.IntegerField(help_text="requires integer input",)
    pop2005 = models.IntegerField('Population',help_text="Country wide population in 2005",)
    fips = models.CharField('FIPS Code',max_length=2, help_text=mark_safe('<a href="http://www.census.gov/geo/www/fips/fips.html">Federal Information Processing Standard Code</a>'))
    iso2 = models.CharField('2 Digit ISO', max_length=2, help_text=mark_safe('<a href="http://www.iso.org/">International Organization for Standardization</a>' ))
    iso3 = models.CharField('3 Digit ISO', max_length=3, help_text=mark_safe('<a href="http://www.iso.org/">International Organization for Standardization</a>' ))
    un = models.IntegerField('United Nations Code',help_text="requires integer input")
    region = models.IntegerField('Region Code',help_text="requires integer input",)
    subregion = models.IntegerField('Sub-Region Code',help_text="requires integer input",)
    lon = models.DecimalField('Longitude',max_digits=8, decimal_places=3, help_text="requires decimal input", )
    lat = models.DecimalField('Latitude',max_digits=7, decimal_places=3, help_text="requires decimal input", )
    
    # GeoDjango specific Field and GeoManager
    geometry = models.MultiPolygonField(srid=4326)
    objects = models.GeoManager()

    class Meta:
        verbose_name_plural = "World Borders"
        
    def __unicode__(self): return self.name



