#!/usr/bin/env python
"""
Given a file of (exposureId, kGray) pairs, as generated by an R
save.table() command, stuff it into the Gray_Extinction table
in the specified db

Run as loadGray <db_name> <gray_file>
"""
import string, sys, os
import glob
import re
import math
import MySQLdb
#
# set up mysql access
mySqlHost = 'lsst10.ncsa.uiuc.edu'
mySqlUser = 'test'
mySqlPasswd = 'globular.test'

# get input args
mySqlDb = sys.argv[1]
grayFile = sys.argv[2]

# open the DB
db = MySQLdb.connect(host=mySqlHost, user=mySqlUser, passwd=mySqlPasswd, db=mySqlDb)
c=db.cursor()

# Get all the pairs from the input file

f = open(grayFile)

query = "TRUNCATE Gray_Extinction; INSERT INTO Gray_Extinction (ccdExposureId, kGray) VALUES "
firstPair = True

for pair in f.readlines():
    (exposureId, grayK) = pair.split()
    if firstPair:
        query = query + "(%s, %s)" % (exposureId, grayK)
        firstPair = False
    else:
        query = query + ",(%s, %s)" % (exposureId, grayK)

print query
c.execute(query)

