# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

"""

Python bindings for detection module

"""

import _detectionLib
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


class PySwigIterator(_object):
    """Proxy of C++ PySwigIterator class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, PySwigIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PySwigIterator, name)
    def __init__(self): raise AttributeError, "No constructor defined"
    __repr__ = _swig_repr
    __swig_destroy__ = _detectionLib.delete_PySwigIterator
    __del__ = lambda self : None;
    def value(*args):
        """value(self) -> PyObject"""
        return _detectionLib.PySwigIterator_value(*args)

    def incr(*args):
        """
        incr(self, size_t n=1) -> PySwigIterator
        incr(self) -> PySwigIterator
        """
        return _detectionLib.PySwigIterator_incr(*args)

    def decr(*args):
        """
        decr(self, size_t n=1) -> PySwigIterator
        decr(self) -> PySwigIterator
        """
        return _detectionLib.PySwigIterator_decr(*args)

    def distance(*args):
        """distance(self, PySwigIterator x) -> ptrdiff_t"""
        return _detectionLib.PySwigIterator_distance(*args)

    def equal(*args):
        """equal(self, PySwigIterator x) -> bool"""
        return _detectionLib.PySwigIterator_equal(*args)

    def copy(*args):
        """copy(self) -> PySwigIterator"""
        return _detectionLib.PySwigIterator_copy(*args)

    def next(*args):
        """next(self) -> PyObject"""
        return _detectionLib.PySwigIterator_next(*args)

    def previous(*args):
        """previous(self) -> PyObject"""
        return _detectionLib.PySwigIterator_previous(*args)

    def advance(*args):
        """advance(self, ptrdiff_t n) -> PySwigIterator"""
        return _detectionLib.PySwigIterator_advance(*args)

    def __eq__(*args):
        """__eq__(self, PySwigIterator x) -> bool"""
        return _detectionLib.PySwigIterator___eq__(*args)

    def __ne__(*args):
        """__ne__(self, PySwigIterator x) -> bool"""
        return _detectionLib.PySwigIterator___ne__(*args)

    def __iadd__(*args):
        """__iadd__(self, ptrdiff_t n) -> PySwigIterator"""
        return _detectionLib.PySwigIterator___iadd__(*args)

    def __isub__(*args):
        """__isub__(self, ptrdiff_t n) -> PySwigIterator"""
        return _detectionLib.PySwigIterator___isub__(*args)

    def __add__(*args):
        """__add__(self, ptrdiff_t n) -> PySwigIterator"""
        return _detectionLib.PySwigIterator___add__(*args)

    def __sub__(*args):
        """
        __sub__(self, ptrdiff_t n) -> PySwigIterator
        __sub__(self, PySwigIterator x) -> ptrdiff_t
        """
        return _detectionLib.PySwigIterator___sub__(*args)

    def __iter__(self): return self
PySwigIterator_swigregister = _detectionLib.PySwigIterator_swigregister
PySwigIterator_swigregister(PySwigIterator)

class ios_base(_object):
    """Proxy of C++ ios_base class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, ios_base, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ios_base, name)
    def __init__(self): raise AttributeError, "No constructor defined"
    __repr__ = _swig_repr
    erase_event = _detectionLib.ios_base_erase_event
    imbue_event = _detectionLib.ios_base_imbue_event
    copyfmt_event = _detectionLib.ios_base_copyfmt_event
    def register_callback(*args):
        """register_callback(self, event_callback __fn, int __index)"""
        return _detectionLib.ios_base_register_callback(*args)

    def flags(*args):
        """
        flags(self) -> fmtflags
        flags(self, fmtflags __fmtfl) -> fmtflags
        """
        return _detectionLib.ios_base_flags(*args)

    def setf(*args):
        """
        setf(self, fmtflags __fmtfl) -> fmtflags
        setf(self, fmtflags __fmtfl, fmtflags __mask) -> fmtflags
        """
        return _detectionLib.ios_base_setf(*args)

    def unsetf(*args):
        """unsetf(self, fmtflags __mask)"""
        return _detectionLib.ios_base_unsetf(*args)

    def precision(*args):
        """
        precision(self) -> streamsize
        precision(self, streamsize __prec) -> streamsize
        """
        return _detectionLib.ios_base_precision(*args)

    def width(*args):
        """
        width(self) -> streamsize
        width(self, streamsize __wide) -> streamsize
        """
        return _detectionLib.ios_base_width(*args)

    def sync_with_stdio(*args):
        """
        sync_with_stdio(bool __sync=True) -> bool
        sync_with_stdio() -> bool
        """
        return _detectionLib.ios_base_sync_with_stdio(*args)

    if _newclass:sync_with_stdio = staticmethod(sync_with_stdio)
    __swig_getmethods__["sync_with_stdio"] = lambda x: sync_with_stdio
    def imbue(*args):
        """imbue(self, locale __loc) -> locale"""
        return _detectionLib.ios_base_imbue(*args)

    def getloc(*args):
        """getloc(self) -> locale"""
        return _detectionLib.ios_base_getloc(*args)

    def xalloc(*args):
        """xalloc() -> int"""
        return _detectionLib.ios_base_xalloc(*args)

    if _newclass:xalloc = staticmethod(xalloc)
    __swig_getmethods__["xalloc"] = lambda x: xalloc
    def iword(*args):
        """iword(self, int __ix) -> long"""
        return _detectionLib.ios_base_iword(*args)

    def pword(*args):
        """pword(self, int __ix) -> void"""
        return _detectionLib.ios_base_pword(*args)

    __swig_destroy__ = _detectionLib.delete_ios_base
    __del__ = lambda self : None;
ios_base_swigregister = _detectionLib.ios_base_swigregister
ios_base_swigregister(ios_base)
cvar = _detectionLib.cvar
ios_base.boolalpha = _detectionLib.cvar.ios_base_boolalpha
ios_base.dec = _detectionLib.cvar.ios_base_dec
ios_base.fixed = _detectionLib.cvar.ios_base_fixed
ios_base.hex = _detectionLib.cvar.ios_base_hex
ios_base.internal = _detectionLib.cvar.ios_base_internal
ios_base.left = _detectionLib.cvar.ios_base_left
ios_base.oct = _detectionLib.cvar.ios_base_oct
ios_base.right = _detectionLib.cvar.ios_base_right
ios_base.scientific = _detectionLib.cvar.ios_base_scientific
ios_base.showbase = _detectionLib.cvar.ios_base_showbase
ios_base.showpoint = _detectionLib.cvar.ios_base_showpoint
ios_base.showpos = _detectionLib.cvar.ios_base_showpos
ios_base.skipws = _detectionLib.cvar.ios_base_skipws
ios_base.unitbuf = _detectionLib.cvar.ios_base_unitbuf
ios_base.uppercase = _detectionLib.cvar.ios_base_uppercase
ios_base.adjustfield = _detectionLib.cvar.ios_base_adjustfield
ios_base.basefield = _detectionLib.cvar.ios_base_basefield
ios_base.floatfield = _detectionLib.cvar.ios_base_floatfield
ios_base.badbit = _detectionLib.cvar.ios_base_badbit
ios_base.eofbit = _detectionLib.cvar.ios_base_eofbit
ios_base.failbit = _detectionLib.cvar.ios_base_failbit
ios_base.goodbit = _detectionLib.cvar.ios_base_goodbit
ios_base.app = _detectionLib.cvar.ios_base_app
ios_base.ate = _detectionLib.cvar.ios_base_ate
ios_base.binary = _detectionLib.cvar.ios_base_binary
ios_base.ios_base_in = _detectionLib.cvar.ios_base_ios_base_in
ios_base.out = _detectionLib.cvar.ios_base_out
ios_base.trunc = _detectionLib.cvar.ios_base_trunc
ios_base.beg = _detectionLib.cvar.ios_base_beg
ios_base.cur = _detectionLib.cvar.ios_base_cur
ios_base.end = _detectionLib.cvar.ios_base_end

def ios_base_sync_with_stdio(*args):
  """
    sync_with_stdio(bool __sync=True) -> bool
    ios_base_sync_with_stdio() -> bool
    """
  return _detectionLib.ios_base_sync_with_stdio(*args)

def ios_base_xalloc(*args):
  """ios_base_xalloc() -> int"""
  return _detectionLib.ios_base_xalloc(*args)

class ios(ios_base):
    """Proxy of C++ ios class"""
    __swig_setmethods__ = {}
    for _s in [ios_base]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, ios, name, value)
    __swig_getmethods__ = {}
    for _s in [ios_base]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ios, name)
    __repr__ = _swig_repr
    def rdstate(*args):
        """rdstate(self) -> iostate"""
        return _detectionLib.ios_rdstate(*args)

    def clear(*args):
        """
        clear(self, iostate __state=goodbit)
        clear(self)
        """
        return _detectionLib.ios_clear(*args)

    def setstate(*args):
        """setstate(self, iostate __state)"""
        return _detectionLib.ios_setstate(*args)

    def good(*args):
        """good(self) -> bool"""
        return _detectionLib.ios_good(*args)

    def eof(*args):
        """eof(self) -> bool"""
        return _detectionLib.ios_eof(*args)

    def fail(*args):
        """fail(self) -> bool"""
        return _detectionLib.ios_fail(*args)

    def bad(*args):
        """bad(self) -> bool"""
        return _detectionLib.ios_bad(*args)

    def exceptions(*args):
        """
        exceptions(self) -> iostate
        exceptions(self, iostate __except)
        """
        return _detectionLib.ios_exceptions(*args)

    def __init__(self, *args): 
        """__init__(self, std::basic_streambuf<(char,std::char_traits<(char)>)> __sb) -> ios"""
        this = _detectionLib.new_ios(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _detectionLib.delete_ios
    __del__ = lambda self : None;
    def tie(*args):
        """
        tie(self) -> ostream
        tie(self, ostream __tiestr) -> ostream
        """
        return _detectionLib.ios_tie(*args)

    def rdbuf(*args):
        """
        rdbuf(self) -> std::basic_streambuf<(char,std::char_traits<(char)>)>
        rdbuf(self, std::basic_streambuf<(char,std::char_traits<(char)>)> __sb) -> std::basic_streambuf<(char,std::char_traits<(char)>)>
        """
        return _detectionLib.ios_rdbuf(*args)

    def copyfmt(*args):
        """copyfmt(self, ios __rhs) -> ios"""
        return _detectionLib.ios_copyfmt(*args)

    def fill(*args):
        """
        fill(self) -> char_type
        fill(self, char_type __ch) -> char_type
        """
        return _detectionLib.ios_fill(*args)

    def imbue(*args):
        """imbue(self, locale __loc) -> locale"""
        return _detectionLib.ios_imbue(*args)

    def narrow(*args):
        """narrow(self, char_type __c, char __dfault) -> char"""
        return _detectionLib.ios_narrow(*args)

    def widen(*args):
        """widen(self, char __c) -> char_type"""
        return _detectionLib.ios_widen(*args)

ios_swigregister = _detectionLib.ios_swigregister
ios_swigregister(ios)

class ostream(ios):
    """Proxy of C++ ostream class"""
    __swig_setmethods__ = {}
    for _s in [ios]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, ostream, name, value)
    __swig_getmethods__ = {}
    for _s in [ios]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ostream, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self, std::basic_streambuf<(char,std::char_traits<(char)>)> __sb) -> ostream"""
        this = _detectionLib.new_ostream(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _detectionLib.delete_ostream
    __del__ = lambda self : None;
    def __lshift__(*args):
        """
        __lshift__(self, ostream __pf) -> ostream
        __lshift__(self, ios __pf) -> ostream
        __lshift__(self, ios_base __pf) -> ostream
        __lshift__(self, long __n) -> ostream
        __lshift__(self, unsigned long __n) -> ostream
        __lshift__(self, bool __n) -> ostream
        __lshift__(self, short __n) -> ostream
        __lshift__(self, unsigned short __n) -> ostream
        __lshift__(self, int __n) -> ostream
        __lshift__(self, unsigned int __n) -> ostream
        __lshift__(self, long long __n) -> ostream
        __lshift__(self, unsigned long long __n) -> ostream
        __lshift__(self, double __f) -> ostream
        __lshift__(self, float __f) -> ostream
        __lshift__(self, long double __f) -> ostream
        __lshift__(self, void __p) -> ostream
        __lshift__(self, std::basic_streambuf<(char,std::char_traits<(char)>)> __sb) -> ostream
        __lshift__(self, std::basic_string<(char,std::char_traits<(char)>,std::allocator<(char)>)> s) -> ostream
        """
        return _detectionLib.ostream___lshift__(*args)

    def put(*args):
        """put(self, char_type __c) -> ostream"""
        return _detectionLib.ostream_put(*args)

    def write(*args):
        """write(self, char_type __s, streamsize __n) -> ostream"""
        return _detectionLib.ostream_write(*args)

    def flush(*args):
        """flush(self) -> ostream"""
        return _detectionLib.ostream_flush(*args)

    def tellp(*args):
        """tellp(self) -> pos_type"""
        return _detectionLib.ostream_tellp(*args)

    def seekp(*args):
        """
        seekp(self, pos_type ?) -> ostream
        seekp(self, off_type ?, seekdir ?) -> ostream
        """
        return _detectionLib.ostream_seekp(*args)

ostream_swigregister = _detectionLib.ostream_swigregister
ostream_swigregister(ostream)
cin = cvar.cin
cout = cvar.cout
cerr = cvar.cerr
clog = cvar.clog

class istream(ios):
    """Proxy of C++ istream class"""
    __swig_setmethods__ = {}
    for _s in [ios]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, istream, name, value)
    __swig_getmethods__ = {}
    for _s in [ios]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, istream, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self, std::basic_streambuf<(char,std::char_traits<(char)>)> __sb) -> istream"""
        this = _detectionLib.new_istream(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _detectionLib.delete_istream
    __del__ = lambda self : None;
    def __rshift__(*args):
        """
        __rshift__(self, istream __pf) -> istream
        __rshift__(self, ios __pf) -> istream
        __rshift__(self, ios_base __pf) -> istream
        __rshift__(self, bool __n) -> istream
        __rshift__(self, short __n) -> istream
        __rshift__(self, unsigned short __n) -> istream
        __rshift__(self, int __n) -> istream
        __rshift__(self, unsigned int __n) -> istream
        __rshift__(self, long __n) -> istream
        __rshift__(self, unsigned long __n) -> istream
        __rshift__(self, long long __n) -> istream
        __rshift__(self, unsigned long long __n) -> istream
        __rshift__(self, float __f) -> istream
        __rshift__(self, double __f) -> istream
        __rshift__(self, long double __f) -> istream
        __rshift__(self, void __p) -> istream
        __rshift__(self, std::basic_streambuf<(char,std::char_traits<(char)>)> __sb) -> istream
        """
        return _detectionLib.istream___rshift__(*args)

    def gcount(*args):
        """gcount(self) -> streamsize"""
        return _detectionLib.istream_gcount(*args)

    def get(*args):
        """
        get(self) -> int_type
        get(self, char_type __c) -> istream
        get(self, char_type __s, streamsize __n, char_type __delim) -> istream
        get(self, char_type __s, streamsize __n) -> istream
        get(self, std::basic_streambuf<(char,std::char_traits<(char)>)> __sb, 
            char_type __delim) -> istream
        get(self, std::basic_streambuf<(char,std::char_traits<(char)>)> __sb) -> istream
        """
        return _detectionLib.istream_get(*args)

    def getline(*args):
        """
        getline(self, char_type __s, streamsize __n, char_type __delim) -> istream
        getline(self, char_type __s, streamsize __n) -> istream
        """
        return _detectionLib.istream_getline(*args)

    def ignore(*args):
        """
        ignore(self, streamsize __n=1, int_type __delim=std::char_traits<char >::eof()) -> istream
        ignore(self, streamsize __n=1) -> istream
        ignore(self) -> istream
        """
        return _detectionLib.istream_ignore(*args)

    def peek(*args):
        """peek(self) -> int_type"""
        return _detectionLib.istream_peek(*args)

    def read(*args):
        """read(self, char_type __s, streamsize __n) -> istream"""
        return _detectionLib.istream_read(*args)

    def readsome(*args):
        """readsome(self, char_type __s, streamsize __n) -> streamsize"""
        return _detectionLib.istream_readsome(*args)

    def putback(*args):
        """putback(self, char_type __c) -> istream"""
        return _detectionLib.istream_putback(*args)

    def unget(*args):
        """unget(self) -> istream"""
        return _detectionLib.istream_unget(*args)

    def sync(*args):
        """sync(self) -> int"""
        return _detectionLib.istream_sync(*args)

    def tellg(*args):
        """tellg(self) -> pos_type"""
        return _detectionLib.istream_tellg(*args)

    def seekg(*args):
        """
        seekg(self, pos_type ?) -> istream
        seekg(self, off_type ?, seekdir ?) -> istream
        """
        return _detectionLib.istream_seekg(*args)

istream_swigregister = _detectionLib.istream_swigregister
istream_swigregister(istream)

class iostream(istream,ostream):
    """Proxy of C++ iostream class"""
    __swig_setmethods__ = {}
    for _s in [istream,ostream]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, iostream, name, value)
    __swig_getmethods__ = {}
    for _s in [istream,ostream]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, iostream, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self, std::basic_streambuf<(char,std::char_traits<(char)>)> __sb) -> iostream"""
        this = _detectionLib.new_iostream(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _detectionLib.delete_iostream
    __del__ = lambda self : None;
iostream_swigregister = _detectionLib.iostream_swigregister
iostream_swigregister(iostream)

endl_cb_ptr = _detectionLib.endl_cb_ptr
endl = _detectionLib.endl
ends_cb_ptr = _detectionLib.ends_cb_ptr
ends = _detectionLib.ends
flush_cb_ptr = _detectionLib.flush_cb_ptr
flush = _detectionLib.flush
class floatArray(_object):
    """Proxy of C++ floatArray class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, floatArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, floatArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self, size_t nelements) -> floatArray"""
        this = _detectionLib.new_floatArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _detectionLib.delete_floatArray
    __del__ = lambda self : None;
    def __getitem__(*args):
        """__getitem__(self, size_t index) -> float"""
        return _detectionLib.floatArray___getitem__(*args)

    def __setitem__(*args):
        """__setitem__(self, size_t index, float value)"""
        return _detectionLib.floatArray___setitem__(*args)

    def cast(*args):
        """cast(self) -> float"""
        return _detectionLib.floatArray_cast(*args)

    def frompointer(*args):
        """frompointer(float t) -> floatArray"""
        return _detectionLib.floatArray_frompointer(*args)

    if _newclass:frompointer = staticmethod(frompointer)
    __swig_getmethods__["frompointer"] = lambda x: frompointer
floatArray_swigregister = _detectionLib.floatArray_swigregister
floatArray_swigregister(floatArray)

def floatArray_frompointer(*args):
  """floatArray_frompointer(float t) -> floatArray"""
  return _detectionLib.floatArray_frompointer(*args)

class doubleArray(_object):
    """Proxy of C++ doubleArray class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, doubleArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, doubleArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self, size_t nelements) -> doubleArray"""
        this = _detectionLib.new_doubleArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _detectionLib.delete_doubleArray
    __del__ = lambda self : None;
    def __getitem__(*args):
        """__getitem__(self, size_t index) -> double"""
        return _detectionLib.doubleArray___getitem__(*args)

    def __setitem__(*args):
        """__setitem__(self, size_t index, double value)"""
        return _detectionLib.doubleArray___setitem__(*args)

    def cast(*args):
        """cast(self) -> double"""
        return _detectionLib.doubleArray_cast(*args)

    def frompointer(*args):
        """frompointer(double t) -> doubleArray"""
        return _detectionLib.doubleArray_frompointer(*args)

    if _newclass:frompointer = staticmethod(frompointer)
    __swig_getmethods__["frompointer"] = lambda x: frompointer
doubleArray_swigregister = _detectionLib.doubleArray_swigregister
doubleArray_swigregister(doubleArray)

def doubleArray_frompointer(*args):
  """doubleArray_frompointer(double t) -> doubleArray"""
  return _detectionLib.doubleArray_frompointer(*args)

def version(HeadURL = r"$HeadURL: svn+ssh://svn.lsstcorp.org/DC2/fw/trunk/python/lsst/fw/Core/detectionLib.i $"):
    """Return a version given a HeadURL string; default: fw's version"""
    return guessSvnVersion(HeadURL)


class Peak(_object):
    """Proxy of C++ Peak class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, Peak, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Peak, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self, int ix, int iy) -> Peak
        __init__(self, float fx=NAN, float fy=NAN) -> Peak
        __init__(self, float fx=NAN) -> Peak
        __init__(self) -> Peak
        """
        this = _detectionLib.new_Peak(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _detectionLib.delete_Peak
    __del__ = lambda self : None;
    def getId(*args):
        """getId(self) -> int"""
        return _detectionLib.Peak_getId(*args)

    def getIx(*args):
        """getIx(self) -> int"""
        return _detectionLib.Peak_getIx(*args)

    def getIy(*args):
        """getIy(self) -> int"""
        return _detectionLib.Peak_getIy(*args)

    def getFx(*args):
        """getFx(self) -> float"""
        return _detectionLib.Peak_getFx(*args)

    def getFy(*args):
        """getFy(self) -> float"""
        return _detectionLib.Peak_getFy(*args)

    def toString(*args):
        """toString(self) -> string"""
        return _detectionLib.Peak_toString(*args)

Peak_swigregister = _detectionLib.Peak_swigregister
Peak_swigregister(Peak)

class Span(_object):
    """Proxy of C++ Span class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, Span, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Span, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self, int y, int x0, int x1) -> Span"""
        this = _detectionLib.new_Span(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _detectionLib.delete_Span
    __del__ = lambda self : None;
    def getX0(*args):
        """getX0(self) -> int"""
        return _detectionLib.Span_getX0(*args)

    def getX1(*args):
        """getX1(self) -> int"""
        return _detectionLib.Span_getX1(*args)

    def getY(*args):
        """getY(self) -> int"""
        return _detectionLib.Span_getY(*args)

    def toString(*args):
        """toString(self) -> string"""
        return _detectionLib.Span_toString(*args)

    def compareByYX(*args):
        """compareByYX(self, void a, void b) -> int"""
        return _detectionLib.Span_compareByYX(*args)

Span_swigregister = _detectionLib.Span_swigregister
Span_swigregister(Span)

class Footprint(_object):
    """Proxy of C++ Footprint class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, Footprint, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Footprint, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self, int nspan=0, BBox2i region=vw::BBox2i(0, 0, 0, 0)) -> Footprint
        __init__(self, int nspan=0) -> Footprint
        __init__(self) -> Footprint
        """
        this = _detectionLib.new_Footprint(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _detectionLib.delete_Footprint
    __del__ = lambda self : None;
    def getId(*args):
        """getId(self) -> int"""
        return _detectionLib.Footprint_getId(*args)

    def getSpans(*args):
        """getSpans(self) -> SpanContainerT"""
        return _detectionLib.Footprint_getSpans(*args)

    def getPeaks(*args):
        """getPeaks(self) -> PeakContainerT"""
        return _detectionLib.Footprint_getPeaks(*args)

    def getNpix(*args):
        """getNpix(self) -> int"""
        return _detectionLib.Footprint_getNpix(*args)

    def addSpan(*args):
        """addSpan(self, int y, int x0, int x1) -> Span"""
        return _detectionLib.Footprint_addSpan(*args)

    def getBBox(*args):
        """getBBox(self) -> BBox2i"""
        return _detectionLib.Footprint_getBBox(*args)

    def getRegion(*args):
        """getRegion(self) -> BBox2i"""
        return _detectionLib.Footprint_getRegion(*args)

    def normalize(*args):
        """normalize(self)"""
        return _detectionLib.Footprint_normalize(*args)

    def setNpix(*args):
        """setNpix(self) -> int"""
        return _detectionLib.Footprint_setNpix(*args)

    def setBBox(*args):
        """setBBox(self)"""
        return _detectionLib.Footprint_setBBox(*args)

    def insertIntoImage(*args):
        """insertIntoImage(self, lsst::fw::Image<(int)> idImage, int id)"""
        return _detectionLib.Footprint_insertIntoImage(*args)

Footprint_swigregister = _detectionLib.Footprint_swigregister
Footprint_swigregister(Footprint)

class PeakPtrT(_object):
    """Proxy of C++ PeakPtrT class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, PeakPtrT, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PeakPtrT, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self, Peak ?) -> PeakPtrT"""
        this = _detectionLib.new_PeakPtrT(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _detectionLib.delete_PeakPtrT
    __del__ = lambda self : None;
    def __deref__(*args):
        """__deref__(self) -> Peak"""
        return _detectionLib.PeakPtrT___deref__(*args)

    def use_count(*args):
        """use_count(self) -> int"""
        return _detectionLib.PeakPtrT_use_count(*args)

    def get(*args):
        """get(self) -> Peak"""
        return _detectionLib.PeakPtrT_get(*args)

    def getId(*args):
        """getId(self) -> int"""
        return _detectionLib.PeakPtrT_getId(*args)

    def getIx(*args):
        """getIx(self) -> int"""
        return _detectionLib.PeakPtrT_getIx(*args)

    def getIy(*args):
        """getIy(self) -> int"""
        return _detectionLib.PeakPtrT_getIy(*args)

    def getFx(*args):
        """getFx(self) -> float"""
        return _detectionLib.PeakPtrT_getFx(*args)

    def getFy(*args):
        """getFy(self) -> float"""
        return _detectionLib.PeakPtrT_getFy(*args)

    def toString(*args):
        """toString(self) -> string"""
        return _detectionLib.PeakPtrT_toString(*args)

PeakPtrT_swigregister = _detectionLib.PeakPtrT_swigregister
PeakPtrT_swigregister(PeakPtrT)

class PeakContainerT(_object):
    """Proxy of C++ PeakContainerT class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, PeakContainerT, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PeakContainerT, name)
    __repr__ = _swig_repr
    def iterator(*args):
        """iterator(self, PyObject PYTHON_SELF) -> PySwigIterator"""
        return _detectionLib.PeakContainerT_iterator(*args)

    def __iter__(self): return self.iterator()
    def __nonzero__(*args):
        """__nonzero__(self) -> bool"""
        return _detectionLib.PeakContainerT___nonzero__(*args)

    def __len__(*args):
        """__len__(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::size_type"""
        return _detectionLib.PeakContainerT___len__(*args)

    def pop(*args):
        """pop(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::value_type"""
        return _detectionLib.PeakContainerT_pop(*args)

    def __getslice__(*args):
        """
        __getslice__(self, std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::difference_type i, 
            std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::difference_type j) -> PeakContainerT
        """
        return _detectionLib.PeakContainerT___getslice__(*args)

    def __setslice__(*args):
        """
        __setslice__(self, std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::difference_type i, 
            std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::difference_type j, 
            PeakContainerT v)
        """
        return _detectionLib.PeakContainerT___setslice__(*args)

    def __delslice__(*args):
        """
        __delslice__(self, std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::difference_type i, 
            std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::difference_type j)
        """
        return _detectionLib.PeakContainerT___delslice__(*args)

    def __delitem__(*args):
        """__delitem__(self, std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::difference_type i)"""
        return _detectionLib.PeakContainerT___delitem__(*args)

    def __getitem__(*args):
        """__getitem__(self, std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::difference_type i) -> std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::value_type"""
        return _detectionLib.PeakContainerT___getitem__(*args)

    def __setitem__(*args):
        """
        __setitem__(self, std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::difference_type i, 
            std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::value_type x)
        """
        return _detectionLib.PeakContainerT___setitem__(*args)

    def append(*args):
        """append(self, std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::value_type x)"""
        return _detectionLib.PeakContainerT_append(*args)

    def empty(*args):
        """empty(self) -> bool"""
        return _detectionLib.PeakContainerT_empty(*args)

    def size(*args):
        """size(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::size_type"""
        return _detectionLib.PeakContainerT_size(*args)

    def clear(*args):
        """clear(self)"""
        return _detectionLib.PeakContainerT_clear(*args)

    def swap(*args):
        """swap(self, PeakContainerT v)"""
        return _detectionLib.PeakContainerT_swap(*args)

    def get_allocator(*args):
        """get_allocator(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::allocator_type"""
        return _detectionLib.PeakContainerT_get_allocator(*args)

    def begin(*args):
        """
        begin(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::iterator
        begin(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::const_iterator
        """
        return _detectionLib.PeakContainerT_begin(*args)

    def end(*args):
        """
        end(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::iterator
        end(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::const_iterator
        """
        return _detectionLib.PeakContainerT_end(*args)

    def rbegin(*args):
        """
        rbegin(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::reverse_iterator
        rbegin(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::const_reverse_iterator
        """
        return _detectionLib.PeakContainerT_rbegin(*args)

    def rend(*args):
        """
        rend(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::reverse_iterator
        rend(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::const_reverse_iterator
        """
        return _detectionLib.PeakContainerT_rend(*args)

    def pop_back(*args):
        """pop_back(self)"""
        return _detectionLib.PeakContainerT_pop_back(*args)

    def erase(*args):
        """
        erase(self, std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::iterator pos) -> std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::iterator
        erase(self, std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::iterator first, 
            std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::iterator last) -> std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::iterator
        """
        return _detectionLib.PeakContainerT_erase(*args)

    def __init__(self, *args): 
        """
        __init__(self) -> PeakContainerT
        __init__(self, PeakContainerT ?) -> PeakContainerT
        __init__(self, std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::size_type size) -> PeakContainerT
        __init__(self, std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::size_type size, 
            std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::value_type value) -> PeakContainerT
        """
        this = _detectionLib.new_PeakContainerT(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(*args):
        """push_back(self, std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::value_type x)"""
        return _detectionLib.PeakContainerT_push_back(*args)

    def front(*args):
        """front(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::value_type"""
        return _detectionLib.PeakContainerT_front(*args)

    def back(*args):
        """back(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::value_type"""
        return _detectionLib.PeakContainerT_back(*args)

    def assign(*args):
        """
        assign(self, std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::size_type n, 
            std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::value_type x)
        """
        return _detectionLib.PeakContainerT_assign(*args)

    def resize(*args):
        """
        resize(self, std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::size_type new_size)
        resize(self, std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::size_type new_size, 
            std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::value_type x)
        """
        return _detectionLib.PeakContainerT_resize(*args)

    def insert(*args):
        """
        insert(self, std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::iterator pos, 
            std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::value_type x) -> std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::iterator
        insert(self, std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::iterator pos, 
            std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::size_type n, 
            std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::value_type x)
        """
        return _detectionLib.PeakContainerT_insert(*args)

    def reserve(*args):
        """reserve(self, std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::size_type n)"""
        return _detectionLib.PeakContainerT_reserve(*args)

    def capacity(*args):
        """capacity(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Peak)>)>::size_type"""
        return _detectionLib.PeakContainerT_capacity(*args)

    __swig_destroy__ = _detectionLib.delete_PeakContainerT
    __del__ = lambda self : None;
PeakContainerT_swigregister = _detectionLib.PeakContainerT_swigregister
PeakContainerT_swigregister(PeakContainerT)

class SpanPtrT(_object):
    """Proxy of C++ SpanPtrT class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, SpanPtrT, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SpanPtrT, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self, Span ?) -> SpanPtrT"""
        this = _detectionLib.new_SpanPtrT(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _detectionLib.delete_SpanPtrT
    __del__ = lambda self : None;
    def __deref__(*args):
        """__deref__(self) -> Span"""
        return _detectionLib.SpanPtrT___deref__(*args)

    def use_count(*args):
        """use_count(self) -> int"""
        return _detectionLib.SpanPtrT_use_count(*args)

    def get(*args):
        """get(self) -> Span"""
        return _detectionLib.SpanPtrT_get(*args)

    def getX0(*args):
        """getX0(self) -> int"""
        return _detectionLib.SpanPtrT_getX0(*args)

    def getX1(*args):
        """getX1(self) -> int"""
        return _detectionLib.SpanPtrT_getX1(*args)

    def getY(*args):
        """getY(self) -> int"""
        return _detectionLib.SpanPtrT_getY(*args)

    def toString(*args):
        """toString(self) -> string"""
        return _detectionLib.SpanPtrT_toString(*args)

    def compareByYX(*args):
        """compareByYX(self, void a, void b) -> int"""
        return _detectionLib.SpanPtrT_compareByYX(*args)

SpanPtrT_swigregister = _detectionLib.SpanPtrT_swigregister
SpanPtrT_swigregister(SpanPtrT)

class SpanContainerT(_object):
    """Proxy of C++ SpanContainerT class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, SpanContainerT, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SpanContainerT, name)
    __repr__ = _swig_repr
    def iterator(*args):
        """iterator(self, PyObject PYTHON_SELF) -> PySwigIterator"""
        return _detectionLib.SpanContainerT_iterator(*args)

    def __iter__(self): return self.iterator()
    def __nonzero__(*args):
        """__nonzero__(self) -> bool"""
        return _detectionLib.SpanContainerT___nonzero__(*args)

    def __len__(*args):
        """__len__(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::size_type"""
        return _detectionLib.SpanContainerT___len__(*args)

    def pop(*args):
        """pop(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::value_type"""
        return _detectionLib.SpanContainerT_pop(*args)

    def __getslice__(*args):
        """
        __getslice__(self, std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::difference_type i, 
            std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::difference_type j) -> SpanContainerT
        """
        return _detectionLib.SpanContainerT___getslice__(*args)

    def __setslice__(*args):
        """
        __setslice__(self, std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::difference_type i, 
            std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::difference_type j, 
            SpanContainerT v)
        """
        return _detectionLib.SpanContainerT___setslice__(*args)

    def __delslice__(*args):
        """
        __delslice__(self, std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::difference_type i, 
            std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::difference_type j)
        """
        return _detectionLib.SpanContainerT___delslice__(*args)

    def __delitem__(*args):
        """__delitem__(self, std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::difference_type i)"""
        return _detectionLib.SpanContainerT___delitem__(*args)

    def __getitem__(*args):
        """__getitem__(self, std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::difference_type i) -> std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::value_type"""
        return _detectionLib.SpanContainerT___getitem__(*args)

    def __setitem__(*args):
        """
        __setitem__(self, std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::difference_type i, 
            std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::value_type x)
        """
        return _detectionLib.SpanContainerT___setitem__(*args)

    def append(*args):
        """append(self, std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::value_type x)"""
        return _detectionLib.SpanContainerT_append(*args)

    def empty(*args):
        """empty(self) -> bool"""
        return _detectionLib.SpanContainerT_empty(*args)

    def size(*args):
        """size(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::size_type"""
        return _detectionLib.SpanContainerT_size(*args)

    def clear(*args):
        """clear(self)"""
        return _detectionLib.SpanContainerT_clear(*args)

    def swap(*args):
        """swap(self, SpanContainerT v)"""
        return _detectionLib.SpanContainerT_swap(*args)

    def get_allocator(*args):
        """get_allocator(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::allocator_type"""
        return _detectionLib.SpanContainerT_get_allocator(*args)

    def begin(*args):
        """
        begin(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::iterator
        begin(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::const_iterator
        """
        return _detectionLib.SpanContainerT_begin(*args)

    def end(*args):
        """
        end(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::iterator
        end(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::const_iterator
        """
        return _detectionLib.SpanContainerT_end(*args)

    def rbegin(*args):
        """
        rbegin(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::reverse_iterator
        rbegin(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::const_reverse_iterator
        """
        return _detectionLib.SpanContainerT_rbegin(*args)

    def rend(*args):
        """
        rend(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::reverse_iterator
        rend(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::const_reverse_iterator
        """
        return _detectionLib.SpanContainerT_rend(*args)

    def pop_back(*args):
        """pop_back(self)"""
        return _detectionLib.SpanContainerT_pop_back(*args)

    def erase(*args):
        """
        erase(self, std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::iterator pos) -> std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::iterator
        erase(self, std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::iterator first, 
            std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::iterator last) -> std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::iterator
        """
        return _detectionLib.SpanContainerT_erase(*args)

    def __init__(self, *args): 
        """
        __init__(self) -> SpanContainerT
        __init__(self, SpanContainerT ?) -> SpanContainerT
        __init__(self, std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::size_type size) -> SpanContainerT
        __init__(self, std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::size_type size, 
            std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::value_type value) -> SpanContainerT
        """
        this = _detectionLib.new_SpanContainerT(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(*args):
        """push_back(self, std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::value_type x)"""
        return _detectionLib.SpanContainerT_push_back(*args)

    def front(*args):
        """front(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::value_type"""
        return _detectionLib.SpanContainerT_front(*args)

    def back(*args):
        """back(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::value_type"""
        return _detectionLib.SpanContainerT_back(*args)

    def assign(*args):
        """
        assign(self, std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::size_type n, 
            std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::value_type x)
        """
        return _detectionLib.SpanContainerT_assign(*args)

    def resize(*args):
        """
        resize(self, std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::size_type new_size)
        resize(self, std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::size_type new_size, 
            std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::value_type x)
        """
        return _detectionLib.SpanContainerT_resize(*args)

    def insert(*args):
        """
        insert(self, std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::iterator pos, 
            std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::value_type x) -> std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::iterator
        insert(self, std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::iterator pos, 
            std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::size_type n, 
            std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::value_type x)
        """
        return _detectionLib.SpanContainerT_insert(*args)

    def reserve(*args):
        """reserve(self, std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::size_type n)"""
        return _detectionLib.SpanContainerT_reserve(*args)

    def capacity(*args):
        """capacity(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Span)>)>::size_type"""
        return _detectionLib.SpanContainerT_capacity(*args)

    __swig_destroy__ = _detectionLib.delete_SpanContainerT
    __del__ = lambda self : None;
SpanContainerT_swigregister = _detectionLib.SpanContainerT_swigregister
SpanContainerT_swigregister(SpanContainerT)

class FootprintPtrT(_object):
    """Proxy of C++ FootprintPtrT class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, FootprintPtrT, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FootprintPtrT, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self, Footprint ?) -> FootprintPtrT"""
        this = _detectionLib.new_FootprintPtrT(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _detectionLib.delete_FootprintPtrT
    __del__ = lambda self : None;
    def __deref__(*args):
        """__deref__(self) -> Footprint"""
        return _detectionLib.FootprintPtrT___deref__(*args)

    def use_count(*args):
        """use_count(self) -> int"""
        return _detectionLib.FootprintPtrT_use_count(*args)

    def get(*args):
        """get(self) -> Footprint"""
        return _detectionLib.FootprintPtrT_get(*args)

    def getId(*args):
        """getId(self) -> int"""
        return _detectionLib.FootprintPtrT_getId(*args)

    def getSpans(*args):
        """getSpans(self) -> SpanContainerT"""
        return _detectionLib.FootprintPtrT_getSpans(*args)

    def getPeaks(*args):
        """getPeaks(self) -> PeakContainerT"""
        return _detectionLib.FootprintPtrT_getPeaks(*args)

    def getNpix(*args):
        """getNpix(self) -> int"""
        return _detectionLib.FootprintPtrT_getNpix(*args)

    def addSpan(*args):
        """addSpan(self, int y, int x0, int x1) -> Span"""
        return _detectionLib.FootprintPtrT_addSpan(*args)

    def getBBox(*args):
        """getBBox(self) -> BBox2i"""
        return _detectionLib.FootprintPtrT_getBBox(*args)

    def getRegion(*args):
        """getRegion(self) -> BBox2i"""
        return _detectionLib.FootprintPtrT_getRegion(*args)

    def normalize(*args):
        """normalize(self)"""
        return _detectionLib.FootprintPtrT_normalize(*args)

    def setNpix(*args):
        """setNpix(self) -> int"""
        return _detectionLib.FootprintPtrT_setNpix(*args)

    def setBBox(*args):
        """setBBox(self)"""
        return _detectionLib.FootprintPtrT_setBBox(*args)

    def insertIntoImage(*args):
        """insertIntoImage(self, lsst::fw::Image<(int)> idImage, int id)"""
        return _detectionLib.FootprintPtrT_insertIntoImage(*args)

FootprintPtrT_swigregister = _detectionLib.FootprintPtrT_swigregister
FootprintPtrT_swigregister(FootprintPtrT)

class FootprintContainerT(_object):
    """Proxy of C++ FootprintContainerT class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, FootprintContainerT, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FootprintContainerT, name)
    __repr__ = _swig_repr
    def iterator(*args):
        """iterator(self, PyObject PYTHON_SELF) -> PySwigIterator"""
        return _detectionLib.FootprintContainerT_iterator(*args)

    def __iter__(self): return self.iterator()
    def __nonzero__(*args):
        """__nonzero__(self) -> bool"""
        return _detectionLib.FootprintContainerT___nonzero__(*args)

    def __len__(*args):
        """__len__(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::size_type"""
        return _detectionLib.FootprintContainerT___len__(*args)

    def pop(*args):
        """pop(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::value_type"""
        return _detectionLib.FootprintContainerT_pop(*args)

    def __getslice__(*args):
        """
        __getslice__(self, std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::difference_type i, 
            std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::difference_type j) -> FootprintContainerT
        """
        return _detectionLib.FootprintContainerT___getslice__(*args)

    def __setslice__(*args):
        """
        __setslice__(self, std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::difference_type i, 
            std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::difference_type j, 
            FootprintContainerT v)
        """
        return _detectionLib.FootprintContainerT___setslice__(*args)

    def __delslice__(*args):
        """
        __delslice__(self, std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::difference_type i, 
            std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::difference_type j)
        """
        return _detectionLib.FootprintContainerT___delslice__(*args)

    def __delitem__(*args):
        """__delitem__(self, std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::difference_type i)"""
        return _detectionLib.FootprintContainerT___delitem__(*args)

    def __getitem__(*args):
        """__getitem__(self, std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::difference_type i) -> std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::value_type"""
        return _detectionLib.FootprintContainerT___getitem__(*args)

    def __setitem__(*args):
        """
        __setitem__(self, std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::difference_type i, 
            std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::value_type x)
        """
        return _detectionLib.FootprintContainerT___setitem__(*args)

    def append(*args):
        """append(self, std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::value_type x)"""
        return _detectionLib.FootprintContainerT_append(*args)

    def empty(*args):
        """empty(self) -> bool"""
        return _detectionLib.FootprintContainerT_empty(*args)

    def size(*args):
        """size(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::size_type"""
        return _detectionLib.FootprintContainerT_size(*args)

    def clear(*args):
        """clear(self)"""
        return _detectionLib.FootprintContainerT_clear(*args)

    def swap(*args):
        """swap(self, FootprintContainerT v)"""
        return _detectionLib.FootprintContainerT_swap(*args)

    def get_allocator(*args):
        """get_allocator(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::allocator_type"""
        return _detectionLib.FootprintContainerT_get_allocator(*args)

    def begin(*args):
        """
        begin(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::iterator
        begin(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::const_iterator
        """
        return _detectionLib.FootprintContainerT_begin(*args)

    def end(*args):
        """
        end(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::iterator
        end(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::const_iterator
        """
        return _detectionLib.FootprintContainerT_end(*args)

    def rbegin(*args):
        """
        rbegin(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::reverse_iterator
        rbegin(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::const_reverse_iterator
        """
        return _detectionLib.FootprintContainerT_rbegin(*args)

    def rend(*args):
        """
        rend(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::reverse_iterator
        rend(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::const_reverse_iterator
        """
        return _detectionLib.FootprintContainerT_rend(*args)

    def pop_back(*args):
        """pop_back(self)"""
        return _detectionLib.FootprintContainerT_pop_back(*args)

    def erase(*args):
        """
        erase(self, std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::iterator pos) -> std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::iterator
        erase(self, std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::iterator first, 
            std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::iterator last) -> std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::iterator
        """
        return _detectionLib.FootprintContainerT_erase(*args)

    def __init__(self, *args): 
        """
        __init__(self) -> FootprintContainerT
        __init__(self, FootprintContainerT ?) -> FootprintContainerT
        __init__(self, std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::size_type size) -> FootprintContainerT
        __init__(self, std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::size_type size, 
            std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::value_type value) -> FootprintContainerT
        """
        this = _detectionLib.new_FootprintContainerT(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(*args):
        """push_back(self, std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::value_type x)"""
        return _detectionLib.FootprintContainerT_push_back(*args)

    def front(*args):
        """front(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::value_type"""
        return _detectionLib.FootprintContainerT_front(*args)

    def back(*args):
        """back(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::value_type"""
        return _detectionLib.FootprintContainerT_back(*args)

    def assign(*args):
        """
        assign(self, std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::size_type n, 
            std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::value_type x)
        """
        return _detectionLib.FootprintContainerT_assign(*args)

    def resize(*args):
        """
        resize(self, std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::size_type new_size)
        resize(self, std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::size_type new_size, 
            std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::value_type x)
        """
        return _detectionLib.FootprintContainerT_resize(*args)

    def insert(*args):
        """
        insert(self, std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::iterator pos, 
            std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::value_type x) -> std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::iterator
        insert(self, std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::iterator pos, 
            std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::size_type n, 
            std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::value_type x)
        """
        return _detectionLib.FootprintContainerT_insert(*args)

    def reserve(*args):
        """reserve(self, std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::size_type n)"""
        return _detectionLib.FootprintContainerT_reserve(*args)

    def capacity(*args):
        """capacity(self) -> std::vector<(boost::shared_ptr<(lsst::detection::Footprint)>)>::size_type"""
        return _detectionLib.FootprintContainerT_capacity(*args)

    __swig_destroy__ = _detectionLib.delete_FootprintContainerT
    __del__ = lambda self : None;
FootprintContainerT_swigregister = _detectionLib.FootprintContainerT_swigregister
FootprintContainerT_swigregister(FootprintContainerT)

class DetectionSetD(_object):
    """Proxy of C++ DetectionSetD class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, DetectionSetD, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DetectionSetD, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self, lsst::fw::MaskedImage<(float,boost::uint8_t)> img, 
            float threshold, string planeName="", int npixMin=1) -> DetectionSetD
        __init__(self, lsst::fw::MaskedImage<(float,boost::uint8_t)> img, 
            float threshold, string planeName="") -> DetectionSetD
        __init__(self, lsst::fw::MaskedImage<(float,boost::uint8_t)> img, 
            float threshold) -> DetectionSetD
        __init__(self, lsst::fw::MaskedImage<(float,boost::uint8_t)> img, 
            float threshold, int x, int y, vector<(lsst::detection::Peak)> peaks=None) -> DetectionSetD
        __init__(self, lsst::fw::MaskedImage<(float,boost::uint8_t)> img, 
            float threshold, int x, int y) -> DetectionSetD
        __init__(self, lsst::detection::DetectionSet<(ImagePixelType,MaskPixelType)> set, 
            int r=0) -> DetectionSetD
        __init__(self, lsst::detection::DetectionSet<(ImagePixelType,MaskPixelType)> set) -> DetectionSetD
        __init__(self, lsst::detection::DetectionSet<(ImagePixelType,MaskPixelType)> footprints1, 
            lsst::detection::DetectionSet<(ImagePixelType,MaskPixelType)> footprints2, 
            int includePeaks) -> DetectionSetD
        """
        this = _detectionLib.new_DetectionSetD(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _detectionLib.delete_DetectionSetD
    __del__ = lambda self : None;
    def getFootprints(*args):
        """getFootprints(self) -> FootprintContainerT"""
        return _detectionLib.DetectionSetD_getFootprints(*args)

    def getRegion(*args):
        """getRegion(self) -> BBox2i"""
        return _detectionLib.DetectionSetD_getRegion(*args)

    def insertIntoImage(*args):
        """insertIntoImage(self, bool relativeIDs) -> boost::shared_ptr<(lsst::fw::Image<(int)>)>"""
        return _detectionLib.DetectionSetD_insertIntoImage(*args)

DetectionSetD_swigregister = _detectionLib.DetectionSetD_swigregister
DetectionSetD_swigregister(DetectionSetD)



