# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _SClient
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


sc_destroy = _SClient.sc_destroy
sc_initialize = _SClient.sc_initialize
sc_instrumentLoad = _SClient.sc_instrumentLoad
sc_instrumentUnloadBatch = _SClient.sc_instrumentUnloadBatch
sc_micRecord = _SClient.sc_micRecord
sc_setMasterVolume = _SClient.sc_setMasterVolume
sc_scoreEvent15 = _SClient.sc_scoreEvent15
sc_start = _SClient.sc_start
sc_stop = _SClient.sc_stop
sc_loop_addScoreEvent15 = _SClient.sc_loop_addScoreEvent15
sc_loop_clear = _SClient.sc_loop_clear
sc_loop_getTick = _SClient.sc_loop_getTick
sc_loop_playing = _SClient.sc_loop_playing
sc_loop_setNumTicks = _SClient.sc_loop_setNumTicks
sc_loop_setTick = _SClient.sc_loop_setTick
sc_loop_setTickDuration = _SClient.sc_loop_setTickDuration


